-- 1. KATEGORİLER TABLOSU (Eğer yoksa)
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name_tr text not null,
  name_en text,
  slug text,
  image_url text -- Resim URL'i burada tutulacak
);

-- RLS (Güvenlik) Ayarları - Herkes okuyabilsin, sadece adminler/giriş yapmışlar yazabilsin
alter table public.categories enable row level security;

create policy "Categories are viewable by everyone"
  on public.categories for select
  using ( true );

create policy "Categories are insertable by authenticated users"
  on public.categories for insert
  with check ( auth.role() = 'authenticated' );

create policy "Categories are updateable by authenticated users"
  on public.categories for update
  using ( auth.role() = 'authenticated' );

create policy "Categories are deletable by authenticated users"
  on public.categories for delete
  using ( auth.role() = 'authenticated' );


-- 2. STORAGE (RESİM YÜKLEME) AYARLARI
-- 'product-images' adında bir bucket oluşturuyoruz (Eğer panelden oluşturmadıysan)
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Storage Politikaları (Policies)
-- Herkes resimleri görebilsin
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'product-images' );

-- Sadece giriş yapmış kullanıcılar (Admin) resim yükleyebilsin
create policy "Authenticated Upload"
  on storage.objects for insert
  with check ( bucket_id = 'product-images' and auth.role() = 'authenticated' );

-- Sadece giriş yapmış kullanıcılar güncelleyebilsin
create policy "Authenticated Update"
  on storage.objects for update
  using ( bucket_id = 'product-images' and auth.role() = 'authenticated' );

-- Sadece giriş yapmış kullanıcılar silebilirsin
create policy "Authenticated Delete"
  on storage.objects for delete
  using ( bucket_id = 'product-images' and auth.role() = 'authenticated' );
